DROP TABLE IF EXISTS dishesFromOrder;
DROP TABLE IF EXISTS dishes CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS type_payment;
DROP TABLE IF EXISTS staff CASCADE;
DROP TABLE IF EXISTS role_staff;
DROP TABLE IF EXISTS statuses CASCADE;
DROP TABLE IF EXISTS typedish;