DROP TABLE IF EXISTS dishes_from_order;
DROP TABLE IF EXISTS dishes;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS type_payment;
DROP TABLE IF EXISTS staff;
DROP TABLE IF EXISTS role_staff;
DROP TABLE IF EXISTS statuses;
DROP TABLE IF EXISTS type_dish;