ALTER TABLE "Staff" DROP CONSTRAINT IF EXISTS "Staff_fk0";

ALTER TABLE "Orders" DROP CONSTRAINT IF EXISTS "Orders_fk0";

ALTER TABLE "Orders" DROP CONSTRAINT IF EXISTS "Orders_fk1";

ALTER TABLE "Dishes" DROP CONSTRAINT IF EXISTS "Dishes_fk0";

ALTER TABLE "DishesFromOrder" DROP CONSTRAINT IF EXISTS "DishesFromOrder_fk0";

ALTER TABLE "DishesFromOrder" DROP CONSTRAINT IF EXISTS "DishesFromOrder_fk1";

DROP TABLE IF EXISTS "Staff";

DROP TABLE IF EXISTS "Orders";

DROP TABLE IF EXISTS "Dishes";

DROP TABLE IF EXISTS "DishesFromOrder";

DROP TABLE IF EXISTS "Statuses";

DROP TABLE IF EXISTS "TypeDish";

DROP TABLE IF EXISTS "Role_staff";

